export interface River {
  id: string;
  name: string;
  slug: string;
  region: string;
  length_km: number | null;
  length_miles: number | null;
  description: string | null;
  origin: string | null;
  mouth: string | null;
  wildlife: string[];
  activities: string[];
  has_gold: boolean;
  swimming_safety: string;
  fishing_season: string | null;
  latitude: number | null;
  longitude: number | null;
  featured: boolean;
  image_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface BlogPost {
  id: string;
  title: string;
  slug: string;
  category: string;
  excerpt: string | null;
  content: string | null;
  image_url: string | null;
  published: boolean;
  published_at: string | null;
  created_at: string;
}

export const rivers: River[] = [
  {
    id: '1',
    name: 'River Thames',
    slug: 'river-thames',
    region: 'England',
    length_km: 346,
    length_miles: 215,
    description: 'The River Thames flows through southern England and London. It is the second longest river in the UK and has played a crucial role in British history, commerce, and culture.',
    origin: 'Thames Head, Gloucestershire',
    mouth: 'Thames Estuary, North Sea',
    wildlife: ['Swans', 'Herons', 'Pike', 'Perch', 'Roach', 'Dace', 'Kingfishers', 'Otters'],
    activities: ['Boating', 'Kayaking', 'Fishing', 'Walking', 'Cycling', 'Wildlife Watching'],
    has_gold: false,
    swimming_safety: 'Swimming in the Thames requires caution due to currents and boat traffic. Use designated safe swimming areas only.',
    fishing_season: 'Coarse fishing: Year-round; Trout: March-September',
    latitude: 51.5074,
    longitude: -0.1278,
    featured: true,
    image_url: 'https://images.pexels.com/photos/460672/pexels-photo-460672.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '2',
    name: 'River Severn',
    slug: 'river-severn',
    region: 'England',
    length_km: 354,
    length_miles: 220,
    description: 'The River Severn is the longest river in the UK, flowing from Wales through western England to the Bristol Channel. It has a distinctive tidal bore and supports diverse wildlife.',
    origin: 'Plynlimon, Wales',
    mouth: 'Bristol Channel',
    wildlife: ['Salmon', 'Lamprey', 'Eels', 'Otters', 'Kingfishers', 'Herons', 'Shad'],
    activities: ['Fishing', 'Kayaking', 'Canoeing', 'Walking', 'Wildlife Watching', 'Bore Watching'],
    has_gold: false,
    swimming_safety: 'Not recommended for swimming due to strong currents and tidal bore. Extremely dangerous in tidal sections.',
    fishing_season: 'Salmon: February-September; Coarse: June-March',
    latitude: 52.5,
    longitude: -2.5,
    featured: true,
    image_url: 'https://images.pexels.com/photos/534164/pexels-photo-534164.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '3',
    name: 'River Tay',
    slug: 'river-tay',
    region: 'Scotland',
    length_km: 193,
    length_miles: 120,
    description: 'The River Tay is Scotland\'s longest river and has the largest discharge of any river in Britain. Famous for Atlantic salmon and known to contain gold deposits.',
    origin: 'Ben Lui, Scottish Highlands',
    mouth: 'Firth of Tay, North Sea',
    wildlife: ['Atlantic Salmon', 'Sea Trout', 'Brown Trout', 'Pike', 'Otters', 'Ospreys', 'Seals'],
    activities: ['Salmon Fishing', 'Gold Panning', 'Kayaking', 'Wildlife Watching', 'Walking', 'Photography'],
    has_gold: true,
    swimming_safety: 'Cold water temperatures year-round. Only swim in designated areas with proper safety equipment.',
    fishing_season: 'Salmon: January-October; Trout: March-September',
    latitude: 56.4,
    longitude: -3.4,
    featured: true,
    image_url: 'https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '4',
    name: 'River Wye',
    slug: 'river-wye',
    region: 'Wales',
    length_km: 215,
    length_miles: 134,
    description: 'The River Wye flows through Wales and England, designated as a Site of Special Scientific Interest. Known for its outstanding natural beauty and important salmon fishery.',
    origin: 'Plynlimon, Wales',
    mouth: 'River Severn Estuary',
    wildlife: ['Salmon', 'Brown Trout', 'Grayling', 'Otters', 'Kingfishers', 'Dippers', 'Peregrine Falcons'],
    activities: ['Canoeing', 'Kayaking', 'Fishing', 'Walking', 'Camping', 'Wildlife Watching'],
    has_gold: false,
    swimming_safety: 'Generally safe in calm sections during summer. Always check local conditions and avoid weirs.',
    fishing_season: 'Salmon: March-October; Trout: March-September',
    latitude: 51.8,
    longitude: -2.6,
    featured: true,
    image_url: 'https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '5',
    name: 'River Trent',
    slug: 'river-trent',
    region: 'England',
    length_km: 297,
    length_miles: 185,
    description: 'The River Trent is England\'s third-longest river, flowing through the Midlands and joining the River Ouse to form the Humber Estuary. Important for navigation and industry.',
    origin: 'Biddulph Moor, Staffordshire',
    mouth: 'Humber Estuary',
    wildlife: ['Pike', 'Barbel', 'Chub', 'Bream', 'Otters', 'Cormorants', 'Herons'],
    activities: ['Coarse Fishing', 'Boating', 'Walking', 'Cycling', 'Wildlife Watching'],
    has_gold: false,
    swimming_safety: 'Not recommended due to strong currents, depth variations, and boat traffic.',
    fishing_season: 'Coarse fishing: June-March; Predatory fish restrictions apply',
    latitude: 53.5,
    longitude: -1.0,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1761279/pexels-photo-1761279.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '6',
    name: 'River Dee',
    slug: 'river-dee-scotland',
    region: 'Scotland',
    length_km: 137,
    length_miles: 85,
    description: 'The River Dee flows through Aberdeenshire and is famous for its salmon fishing and royal connections. Known to contain gold deposits.',
    origin: 'Cairngorms, Scottish Highlands',
    mouth: 'North Sea at Aberdeen',
    wildlife: ['Atlantic Salmon', 'Sea Trout', 'Brown Trout', 'Otters', 'Ospreys', 'Red Squirrels'],
    activities: ['Salmon Fishing', 'Gold Panning', 'Walking', 'Mountain Biking', 'Wildlife Watching'],
    has_gold: true,
    swimming_safety: 'Very cold water year-round. Only for experienced wild swimmers with proper equipment.',
    fishing_season: 'Salmon: February-September; Trout: March-September',
    latitude: 57.1,
    longitude: -2.9,
    featured: true,
    image_url: 'https://images.pexels.com/photos/1118877/pexels-photo-1118877.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '7',
    name: 'River Spey',
    slug: 'river-spey',
    region: 'Scotland',
    length_km: 172,
    length_miles: 107,
    description: 'The River Spey is Scotland\'s second longest river and fastest flowing. Famous for salmon fishing and the whisky distilleries along its banks.',
    origin: 'Loch Spey, Scottish Highlands',
    mouth: 'Moray Firth',
    wildlife: ['Atlantic Salmon', 'Sea Trout', 'Ospreys', 'Otters', 'Pine Martens', 'Capercaillie'],
    activities: ['Salmon Fishing', 'Rafting', 'Canoeing', 'Whisky Trail', 'Walking', 'Wildlife Watching'],
    has_gold: false,
    swimming_safety: 'Fast-flowing and cold. Only for experienced swimmers in designated calm pools.',
    fishing_season: 'Salmon: February-September; Trout: March-September',
    latitude: 57.3,
    longitude: -3.3,
    featured: true,
    image_url: 'https://images.pexels.com/photos/2901209/pexels-photo-2901209.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '8',
    name: 'River Ouse',
    slug: 'river-ouse-yorkshire',
    region: 'England',
    length_km: 89,
    length_miles: 52,
    description: 'The River Ouse flows through York and North Yorkshire before joining the River Trent. Rich in history with Roman and Viking connections.',
    origin: 'Ouse Gill Beck, North Yorkshire',
    mouth: 'Humber Estuary',
    wildlife: ['Pike', 'Perch', 'Roach', 'Bream', 'Otters', 'Kingfishers', 'Grey Herons'],
    activities: ['Coarse Fishing', 'Boating', 'Rowing', 'Walking', 'Historic Tours'],
    has_gold: false,
    swimming_safety: 'Not recommended due to tidal influences, depth variations, and water quality concerns.',
    fishing_season: 'Coarse fishing: June-March',
    latitude: 53.9,
    longitude: -1.08,
    featured: false,
    image_url: 'https://images.pexels.com/photos/2376997/pexels-photo-2376997.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '9',
    name: 'River Clyde',
    slug: 'river-clyde',
    region: 'Scotland',
    length_km: 176,
    length_miles: 109,
    description: 'The River Clyde flows through Glasgow and was once one of the world\'s most important shipbuilding rivers. Now undergoing environmental regeneration.',
    origin: 'Lowther Hills, South Lanarkshire',
    mouth: 'Firth of Clyde',
    wildlife: ['Salmon', 'Sea Trout', 'Otters', 'Seals', 'Cormorants', 'Swans'],
    activities: ['Walking', 'Cycling', 'Fishing', 'Kayaking', 'Heritage Tours'],
    has_gold: false,
    swimming_safety: 'Not recommended in urban sections. Rural upper sections safer during summer.',
    fishing_season: 'Salmon: February-October; Trout: March-September',
    latitude: 55.9,
    longitude: -4.4,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1287145/pexels-photo-1287145.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '10',
    name: 'River Avon',
    slug: 'river-avon-warwickshire',
    region: 'England',
    length_km: 154,
    length_miles: 96,
    description: 'The Warwickshire Avon flows through Shakespeare country. Known for its scenic beauty and connection to Stratford-upon-Avon.',
    origin: 'Naseby, Northamptonshire',
    mouth: 'River Severn at Tewkesbury',
    wildlife: ['Pike', 'Chub', 'Barbel', 'Kingfishers', 'Otters', 'Swans', 'Water Voles'],
    activities: ['Narrowboat Cruising', 'Fishing', 'Walking', 'Cycling', 'Theatre Tours'],
    has_gold: false,
    swimming_safety: 'Some safe swimming spots in upper reaches during summer. Always check locally.',
    fishing_season: 'Coarse fishing: June-March',
    latitude: 52.2,
    longitude: -1.7,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1761279/pexels-photo-1761279.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '11',
    name: 'River Mersey',
    slug: 'river-mersey',
    region: 'England',
    length_km: 113,
    length_miles: 70,
    description: 'The River Mersey flows through Liverpool and Manchester, forming a major estuary. Historically vital for trade and industry in Northwest England.',
    origin: 'Stockport, Greater Manchester',
    mouth: 'Liverpool Bay, Irish Sea',
    wildlife: ['Grey Seals', 'Bottlenose Dolphins', 'Cormorants', 'Herons', 'Flounder', 'Bass'],
    activities: ['Walking', 'Cycling', 'Heritage Tours', 'Wildlife Watching'],
    has_gold: false,
    swimming_safety: 'Not recommended due to strong tidal currents and industrial history. Water quality has improved but caution advised.',
    fishing_season: 'Coarse fishing: Year-round with restrictions',
    latitude: 53.4,
    longitude: -3.0,
    featured: false,
    image_url: 'https://images.pexels.com/photos/534164/pexels-photo-534164.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '12',
    name: 'River Tyne',
    slug: 'river-tyne',
    region: 'England',
    length_km: 118,
    length_miles: 73,
    description: 'The River Tyne flows through Newcastle and was central to shipbuilding and coal exports. Now a regenerated waterway with improved water quality.',
    origin: 'North Pennines',
    mouth: 'North Sea at Tynemouth',
    wildlife: ['Salmon', 'Sea Trout', 'Otters', 'Seals', 'Kingfishers'],
    activities: ['Walking', 'Cycling', 'Salmon Fishing', 'Heritage Tours', 'Rowing'],
    has_gold: false,
    swimming_safety: 'Not recommended in tidal sections. Upper reaches safer but still requires caution.',
    fishing_season: 'Salmon: February-October; Trout: March-September',
    latitude: 54.97,
    longitude: -1.61,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1761279/pexels-photo-1761279.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '13',
    name: 'River Tees',
    slug: 'river-tees',
    region: 'England',
    length_km: 137,
    length_miles: 85,
    description: 'The River Tees rises in the Pennines and flows through Teesside. Features the spectacular High Force waterfall.',
    origin: 'Cross Fell, Pennines',
    mouth: 'North Sea at Middlesbrough',
    wildlife: ['Brown Trout', 'Grayling', 'Otters', 'Dippers', 'Kingfishers', 'Herons'],
    activities: ['Walking', 'Fishing', 'White Water Kayaking', 'Wildlife Watching', 'Photography'],
    has_gold: false,
    swimming_safety: 'Upper reaches suitable for wild swimming in summer. Avoid industrial areas and fast-flowing sections.',
    fishing_season: 'Trout: March-September; Coarse: June-March',
    latitude: 54.57,
    longitude: -1.24,
    featured: false,
    image_url: 'https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '14',
    name: 'River Wear',
    slug: 'river-wear',
    region: 'England',
    length_km: 97,
    length_miles: 60,
    description: 'The River Wear flows through Durham City, creating a dramatic horseshoe bend around the historic cathedral and castle.',
    origin: 'Wearhead, County Durham',
    mouth: 'North Sea at Sunderland',
    wildlife: ['Salmon', 'Sea Trout', 'Otters', 'Kingfishers', 'Grey Herons'],
    activities: ['Walking', 'Rowing', 'Fishing', 'Heritage Tours', 'Photography'],
    has_gold: false,
    swimming_safety: 'Not recommended due to currents and water quality. Upper reaches cleaner but still requires caution.',
    fishing_season: 'Salmon: February-October; Trout: March-September',
    latitude: 54.9,
    longitude: -1.54,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '15',
    name: 'River Humber',
    slug: 'river-humber',
    region: 'England',
    length_km: 62,
    length_miles: 38,
    description: 'The Humber is a large tidal estuary formed by the confluence of the Trent and Ouse. One of the most important estuaries in England.',
    origin: 'Confluence of Trent and Ouse',
    mouth: 'North Sea',
    wildlife: ['Grey Seals', 'Bottlenose Dolphins', 'Porpoises', 'Waders', 'Wildfowl'],
    activities: ['Wildlife Watching', 'Bird Watching', 'Heritage Tours'],
    has_gold: false,
    swimming_safety: 'Extremely dangerous due to strong tidal currents, depth, and cold water. Swimming not advised.',
    fishing_season: 'Sea fishing: Year-round',
    latitude: 53.7,
    longitude: -0.3,
    featured: false,
    image_url: 'https://images.pexels.com/photos/534164/pexels-photo-534164.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '16',
    name: 'River Great Ouse',
    slug: 'river-great-ouse',
    region: 'England',
    length_km: 230,
    length_miles: 143,
    description: 'The Great Ouse flows through East Anglia, an important river for drainage and navigation. Passes through Bedford and Ely.',
    origin: 'Syresham, Northamptonshire',
    mouth: 'The Wash',
    wildlife: ['Pike', 'Perch', 'Bream', 'Otters', 'Water Voles', 'Kingfishers', 'Herons'],
    activities: ['Boating', 'Fishing', 'Walking', 'Cycling', 'Wildlife Watching'],
    has_gold: false,
    swimming_safety: 'Some designated swimming areas. Generally slow-flowing but caution needed near locks and weirs.',
    fishing_season: 'Coarse fishing: June-March',
    latitude: 52.35,
    longitude: 0.2,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1761279/pexels-photo-1761279.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '17',
    name: 'River Avon (Bristol)',
    slug: 'river-avon-bristol',
    region: 'England',
    length_km: 121,
    length_miles: 75,
    description: 'The Bristol Avon flows through Bath and Bristol, famous for the Avon Gorge and Clifton Suspension Bridge.',
    origin: 'Acton Turville, Gloucestershire',
    mouth: 'Bristol Channel at Avonmouth',
    wildlife: ['Pike', 'Chub', 'Roach', 'Kingfishers', 'Herons', 'Otters'],
    activities: ['Walking', 'Cycling', 'Fishing', 'Heritage Tours', 'Kayaking'],
    has_gold: false,
    swimming_safety: 'Not recommended due to tidal influence and strong currents in lower reaches.',
    fishing_season: 'Coarse fishing: June-March',
    latitude: 51.45,
    longitude: -2.6,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '18',
    name: 'River Medway',
    slug: 'river-medway',
    region: 'England',
    length_km: 113,
    length_miles: 70,
    description: 'The River Medway flows through Kent, an important waterway with historic dockyards at Chatham.',
    origin: 'Turners Hill, West Sussex',
    mouth: 'Thames Estuary',
    wildlife: ['Pike', 'Perch', 'Roach', 'Herons', 'Kingfishers', 'Swans'],
    activities: ['Boating', 'Fishing', 'Walking', 'Heritage Tours', 'Cycling'],
    has_gold: false,
    swimming_safety: 'Not recommended in tidal sections. Upper reaches safer but always check locally.',
    fishing_season: 'Coarse fishing: June-March',
    latitude: 51.4,
    longitude: 0.6,
    featured: false,
    image_url: 'https://images.pexels.com/photos/460672/pexels-photo-460672.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '19',
    name: 'River Lea',
    slug: 'river-lea',
    region: 'England',
    length_km: 74,
    length_miles: 46,
    description: 'The River Lea flows through Hertfordshire and East London, joining the Thames. Important for London\'s water supply and industry.',
    origin: 'Leagrave, Bedfordshire',
    mouth: 'River Thames at Bow Creek',
    wildlife: ['Pike', 'Perch', 'Roach', 'Kingfishers', 'Herons', 'Coots'],
    activities: ['Walking', 'Cycling', 'Fishing', 'Canoeing', 'Wildlife Watching'],
    has_gold: false,
    swimming_safety: 'Not recommended due to water quality and boat traffic.',
    fishing_season: 'Coarse fishing: June-March',
    latitude: 51.7,
    longitude: -0.02,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1761279/pexels-photo-1761279.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '20',
    name: 'River Tamar',
    slug: 'river-tamar',
    region: 'England',
    length_km: 97,
    length_miles: 60,
    description: 'The River Tamar forms most of the border between Devon and Cornwall, flowing into Plymouth Sound.',
    origin: 'Woolley Moor, North Cornwall',
    mouth: 'Plymouth Sound',
    wildlife: ['Salmon', 'Sea Trout', 'Otters', 'Kingfishers', 'Herons', 'Egrets'],
    activities: ['Fishing', 'Kayaking', 'Walking', 'Wildlife Watching', 'Heritage Tours'],
    has_gold: false,
    swimming_safety: 'Some safe swimming spots in upper reaches. Tidal sections require caution.',
    fishing_season: 'Salmon: February-October; Trout: March-September',
    latitude: 50.4,
    longitude: -4.2,
    featured: false,
    image_url: 'https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '21',
    name: 'River Exe',
    slug: 'river-exe',
    region: 'England',
    length_km: 82,
    length_miles: 51,
    description: 'The River Exe flows through Devon to Exeter and forms a beautiful estuary. Popular for water sports and wildlife.',
    origin: 'Exe Head, Exmoor',
    mouth: 'English Channel at Exmouth',
    wildlife: ['Salmon', 'Sea Trout', 'Otters', 'Avocets', 'Black-tailed Godwits', 'Dunlin'],
    activities: ['Fishing', 'Kayaking', 'Sailing', 'Bird Watching', 'Walking', 'Cycling'],
    has_gold: false,
    swimming_safety: 'Good swimming spots in upper river. Estuary suitable for experienced swimmers.',
    fishing_season: 'Salmon: February-September; Trout: March-September',
    latitude: 50.6,
    longitude: -3.4,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '22',
    name: 'River Dart',
    slug: 'river-dart',
    region: 'England',
    length_km: 75,
    length_miles: 47,
    description: 'The River Dart rises on Dartmoor and flows through a spectacular wooded valley to Dartmouth.',
    origin: 'Dartmoor, Devon',
    mouth: 'English Channel at Dartmouth',
    wildlife: ['Salmon', 'Sea Trout', 'Otters', 'Kingfishers', 'Herons', 'Dippers'],
    activities: ['Kayaking', 'Canoeing', 'Fishing', 'Wild Swimming', 'Walking'],
    has_gold: false,
    swimming_safety: 'Popular wild swimming river with many good spots. Always check flow conditions.',
    fishing_season: 'Salmon: February-September; Trout: March-September',
    latitude: 50.35,
    longitude: -3.85,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1118877/pexels-photo-1118877.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '23',
    name: 'River Don (South Yorkshire)',
    slug: 'river-don-south-yorkshire',
    region: 'England',
    length_km: 112,
    length_miles: 70,
    description: 'The River Don flows through Sheffield and Doncaster, historically important for steel industry.',
    origin: 'Peak District, South Yorkshire',
    mouth: 'River Ouse at Goole',
    wildlife: ['Pike', 'Perch', 'Chub', 'Otters', 'Kingfishers', 'Herons'],
    activities: ['Fishing', 'Walking', 'Cycling', 'Canoeing'],
    has_gold: false,
    swimming_safety: 'Not recommended due to water quality in industrial areas. Upper reaches cleaner.',
    fishing_season: 'Coarse fishing: June-March',
    latitude: 53.5,
    longitude: -1.15,
    featured: false,
    image_url: 'https://images.pexels.com/photos/534164/pexels-photo-534164.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '24',
    name: 'River Aire',
    slug: 'river-aire',
    region: 'England',
    length_km: 117,
    length_miles: 73,
    description: 'The River Aire flows through Leeds and the Yorkshire Dales, featuring spectacular waterfalls at Malham.',
    origin: 'Malham, Yorkshire Dales',
    mouth: 'River Ouse near Goole',
    wildlife: ['Brown Trout', 'Grayling', 'Otters', 'Kingfishers', 'Dippers', 'Herons'],
    activities: ['Walking', 'Fishing', 'Kayaking', 'Heritage Tours', 'Photography'],
    has_gold: false,
    swimming_safety: 'Upper reaches have some swimming spots. Avoid urban sections.',
    fishing_season: 'Trout: March-September; Coarse: June-March',
    latitude: 53.8,
    longitude: -1.55,
    featured: false,
    image_url: 'https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '25',
    name: 'River Calder',
    slug: 'river-calder',
    region: 'England',
    length_km: 89,
    length_miles: 55,
    description: 'The River Calder flows through West Yorkshire, joining the River Aire at Castleford.',
    origin: 'Cliviger, Lancashire',
    mouth: 'River Aire at Castleford',
    wildlife: ['Pike', 'Chub', 'Roach', 'Kingfishers', 'Herons', 'Cormorants'],
    activities: ['Walking', 'Cycling', 'Fishing', 'Heritage Canal Tours'],
    has_gold: false,
    swimming_safety: 'Not recommended due to water quality and industrial history.',
    fishing_season: 'Coarse fishing: June-March',
    latitude: 53.7,
    longitude: -1.5,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1761279/pexels-photo-1761279.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '26',
    name: 'River Eden (Cumbria)',
    slug: 'river-eden-cumbria',
    region: 'England',
    length_km: 145,
    length_miles: 90,
    description: 'The River Eden flows through Cumbria, one of England\'s finest salmon rivers and a designated Special Area of Conservation.',
    origin: 'Mallerstang, Yorkshire Dales',
    mouth: 'Solway Firth',
    wildlife: ['Atlantic Salmon', 'Sea Trout', 'Brown Trout', 'Otters', 'Ospreys', 'Kingfishers'],
    activities: ['Salmon Fishing', 'Walking', 'Wildlife Watching', 'Kayaking', 'Swimming'],
    has_gold: false,
    swimming_safety: 'Several popular wild swimming spots. Generally safe in summer but check flow levels.',
    fishing_season: 'Salmon: January-October; Trout: March-September',
    latitude: 54.9,
    longitude: -2.9,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1118877/pexels-photo-1118877.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '27',
    name: 'River Ribble',
    slug: 'river-ribble',
    region: 'England',
    length_km: 121,
    length_miles: 75,
    description: 'The River Ribble flows through Lancashire from the Yorkshire Dales to the Irish Sea.',
    origin: 'Ribblehead, Yorkshire Dales',
    mouth: 'Irish Sea near Preston',
    wildlife: ['Salmon', 'Sea Trout', 'Otters', 'Herons', 'Oystercatchers', 'Curlews'],
    activities: ['Fishing', 'Walking', 'Cycling', 'Bird Watching', 'Wildlife Watching'],
    has_gold: false,
    swimming_safety: 'Some swimming spots in upper reaches. Tidal sections dangerous.',
    fishing_season: 'Salmon: March-October; Trout: March-September',
    latitude: 53.7,
    longitude: -2.8,
    featured: false,
    image_url: 'https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '28',
    name: 'River Lune',
    slug: 'river-lune',
    region: 'England',
    length_km: 85,
    length_miles: 53,
    description: 'The River Lune flows through Lancashire, passing Lancaster and featuring the spectacular Lune Gorge.',
    origin: 'Newbiggin-on-Lune, Cumbria',
    mouth: 'Morecambe Bay',
    wildlife: ['Salmon', 'Sea Trout', 'Otters', 'Kingfishers', 'Herons', 'Sand Martins'],
    activities: ['Fishing', 'Kayaking', 'Walking', 'Cycling', 'Wildlife Watching'],
    has_gold: false,
    swimming_safety: 'Some good swimming spots in upper and middle reaches. Check tidal times near mouth.',
    fishing_season: 'Salmon: February-October; Trout: March-September',
    latitude: 54.05,
    longitude: -2.8,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '29',
    name: 'River Derwent (Derbyshire)',
    slug: 'river-derwent-derbyshire',
    region: 'England',
    length_km: 106,
    length_miles: 66,
    description: 'The Derbyshire Derwent flows through the Peak District and Derby, joining the River Trent.',
    origin: 'Bleaklow, Peak District',
    mouth: 'River Trent',
    wildlife: ['Brown Trout', 'Grayling', 'Chub', 'Otters', 'Kingfishers', 'Dippers'],
    activities: ['Fishing', 'Walking', 'Cycling', 'White Water Kayaking', 'Wildlife Watching'],
    has_gold: false,
    swimming_safety: 'Some swimming spots in Peak District sections. Urban areas not recommended.',
    fishing_season: 'Trout: March-September; Coarse: June-March',
    latitude: 53.0,
    longitude: -1.5,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1118877/pexels-photo-1118877.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '30',
    name: 'River Itchen',
    slug: 'river-itchen',
    region: 'England',
    length_km: 45,
    length_miles: 28,
    description: 'The River Itchen is a famous Hampshire chalk stream, one of the world\'s finest trout fishing rivers.',
    origin: 'Hinton Ampner, Hampshire',
    mouth: 'Southampton Water',
    wildlife: ['Brown Trout', 'Grayling', 'Water Voles', 'Otters', 'Kingfishers', 'Water Crowfoot'],
    activities: ['Trout Fishing', 'Walking', 'Wildlife Watching', 'Photography'],
    has_gold: false,
    swimming_safety: 'Some designated swimming areas. Crystal-clear chalk stream water but cold year-round.',
    fishing_season: 'Trout: April-October (highly regulated)',
    latitude: 51.05,
    longitude: -1.3,
    featured: false,
    image_url: 'https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '31',
    name: 'River Test',
    slug: 'river-test',
    region: 'England',
    length_km: 64,
    length_miles: 40,
    description: 'The River Test is England\'s premier chalk stream, world-famous for fly fishing. Crystal-clear waters support unique ecosystems.',
    origin: 'Ashe, Hampshire',
    mouth: 'Southampton Water',
    wildlife: ['Brown Trout', 'Grayling', 'Water Voles', 'Otters', 'Kingfishers', 'Dragonflies'],
    activities: ['Trout Fishing', 'Walking', 'Wildlife Watching', 'Photography'],
    has_gold: false,
    swimming_safety: 'Limited swimming access. Mostly private fishing waters. Cold water temperatures.',
    fishing_season: 'Trout: May-September (strictly controlled)',
    latitude: 51.0,
    longitude: -1.5,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1118877/pexels-photo-1118877.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '32',
    name: 'River Forth',
    slug: 'river-forth',
    region: 'Scotland',
    length_km: 47,
    length_miles: 29,
    description: 'The River Forth flows through Stirling and forms the Firth of Forth estuary. Historically significant for Scottish battles.',
    origin: 'Loch Ard, Trossachs',
    mouth: 'Firth of Forth, North Sea',
    wildlife: ['Salmon', 'Sea Trout', 'Seals', 'Porpoises', 'Wading Birds'],
    activities: ['Walking', 'Heritage Tours', 'Bird Watching', 'Fishing'],
    has_gold: false,
    swimming_safety: 'Not recommended due to tidal currents in estuary. Upper river sections safer.',
    fishing_season: 'Salmon: February-October',
    latitude: 56.1,
    longitude: -3.9,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '33',
    name: 'River Tweed',
    slug: 'river-tweed',
    region: 'Scotland',
    length_km: 156,
    length_miles: 97,
    description: 'The River Tweed forms part of the Scotland-England border. One of Britain\'s greatest salmon rivers.',
    origin: 'Tweed\'s Well, Scottish Borders',
    mouth: 'North Sea at Berwick-upon-Tweed',
    wildlife: ['Atlantic Salmon', 'Sea Trout', 'Brown Trout', 'Otters', 'Ospreys', 'Seals'],
    activities: ['Salmon Fishing', 'Walking', 'Cycling', 'Wildlife Watching', 'Heritage Tours'],
    has_gold: false,
    swimming_safety: 'Cold water. Some swimming spots but requires caution and experience.',
    fishing_season: 'Salmon: February-November; Trout: March-September',
    latitude: 55.77,
    longitude: -2.0,
    featured: false,
    image_url: 'https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '34',
    name: 'River Don (Aberdeenshire)',
    slug: 'river-don-aberdeenshire',
    region: 'Scotland',
    length_km: 131,
    length_miles: 82,
    description: 'The Aberdeenshire Don flows through the Grampians to Aberdeen. Important salmon river with scenic valleys.',
    origin: 'Cairngorms, Aberdeenshire',
    mouth: 'North Sea at Aberdeen',
    wildlife: ['Atlantic Salmon', 'Sea Trout', 'Brown Trout', 'Otters', 'Red Squirrels'],
    activities: ['Salmon Fishing', 'Walking', 'Wildlife Watching', 'Cycling'],
    has_gold: true,
    swimming_safety: 'Very cold water. Only for experienced wild swimmers.',
    fishing_season: 'Salmon: February-October; Trout: March-September',
    latitude: 57.15,
    longitude: -2.1,
    featured: false,
    image_url: 'https://images.pexels.com/photos/2901209/pexels-photo-2901209.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '35',
    name: 'River Ness',
    slug: 'river-ness',
    region: 'Scotland',
    length_km: 11,
    length_miles: 7,
    description: 'The River Ness flows from Loch Ness through Inverness to the Moray Firth. Short but important salmon river.',
    origin: 'Loch Ness',
    mouth: 'Moray Firth',
    wildlife: ['Atlantic Salmon', 'Sea Trout', 'Seals', 'Dolphins', 'Otters'],
    activities: ['Salmon Fishing', 'Walking', 'Wildlife Watching', 'Heritage Tours'],
    has_gold: false,
    swimming_safety: 'Cold water. Strong currents near weirs. Not recommended.',
    fishing_season: 'Salmon: January-September',
    latitude: 57.48,
    longitude: -4.22,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1118877/pexels-photo-1118877.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '36',
    name: 'River Usk',
    slug: 'river-usk',
    region: 'Wales',
    length_km: 120,
    length_miles: 75,
    description: 'The River Usk flows through South Wales, designated a Special Area of Conservation. Excellent for salmon and trout fishing.',
    origin: 'Carmarthen Fan, Brecon Beacons',
    mouth: 'Severn Estuary at Newport',
    wildlife: ['Atlantic Salmon', 'Sea Trout', 'Brown Trout', 'Otters', 'Kingfishers', 'Dippers'],
    activities: ['Salmon Fishing', 'Canoeing', 'Walking', 'Wildlife Watching', 'Cycling'],
    has_gold: false,
    swimming_safety: 'Some good swimming spots in upper reaches. Check flow levels.',
    fishing_season: 'Salmon: March-October; Trout: March-September',
    latitude: 51.6,
    longitude: -2.98,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '37',
    name: 'River Taff',
    slug: 'river-taff',
    region: 'Wales',
    length_km: 64,
    length_miles: 40,
    description: 'The River Taff flows through Cardiff, historically important for coal industry. Now a regenerated urban river.',
    origin: 'Brecon Beacons',
    mouth: 'Bristol Channel at Cardiff',
    wildlife: ['Brown Trout', 'Salmon', 'Otters', 'Kingfishers', 'Herons'],
    activities: ['Walking', 'Cycling', 'Fishing', 'Heritage Tours'],
    has_gold: false,
    swimming_safety: 'Not recommended in urban sections. Upper reaches have some spots.',
    fishing_season: 'Salmon: March-October; Trout: March-September',
    latitude: 51.48,
    longitude: -3.18,
    featured: false,
    image_url: 'https://images.pexels.com/photos/534164/pexels-photo-534164.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '38',
    name: 'River Teifi',
    slug: 'river-teifi',
    region: 'Wales',
    length_km: 121,
    length_miles: 75,
    description: 'The River Teifi flows through West Wales, famous for salmon and sea trout fishing. Forms spectacular gorges.',
    origin: 'Teifi Pools, Cambrian Mountains',
    mouth: 'Cardigan Bay',
    wildlife: ['Atlantic Salmon', 'Sea Trout', 'Otters', 'Grey Seals', 'Dolphins'],
    activities: ['Salmon Fishing', 'Canoeing', 'Kayaking', 'Walking', 'Wildlife Watching'],
    has_gold: false,
    swimming_safety: 'Several popular swimming spots. Generally safe in summer.',
    fishing_season: 'Salmon: March-October; Trout: March-September',
    latitude: 52.1,
    longitude: -4.5,
    featured: false,
    image_url: 'https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '39',
    name: 'River Tywi',
    slug: 'river-tywi',
    region: 'Wales',
    length_km: 120,
    length_miles: 75,
    description: 'The River Tywi (Towy) is the longest river entirely in Wales. Excellent for salmon and sea trout.',
    origin: 'Cambrian Mountains',
    mouth: 'Carmarthen Bay',
    wildlife: ['Atlantic Salmon', 'Sea Trout', 'Otters', 'Red Kites', 'Herons'],
    activities: ['Salmon Fishing', 'Canoeing', 'Walking', 'Wildlife Watching', 'Cycling'],
    has_gold: false,
    swimming_safety: 'Some good swimming locations. Popular in summer months.',
    fishing_season: 'Salmon: March-October; Trout: March-September',
    latitude: 51.8,
    longitude: -4.3,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1118877/pexels-photo-1118877.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '40',
    name: 'River Dee (Wales)',
    slug: 'river-dee-wales',
    region: 'Wales',
    length_km: 113,
    length_miles: 70,
    description: 'The Welsh River Dee (Afon Dyfrdwy) flows from Snowdonia through Chester to the Irish Sea.',
    origin: 'Dduallt, Snowdonia',
    mouth: 'Irish Sea at Chester',
    wildlife: ['Salmon', 'Sea Trout', 'Otters', 'Kingfishers', 'Herons', 'Wading Birds'],
    activities: ['Salmon Fishing', 'Kayaking', 'Walking', 'White Water Rafting', 'Wildlife Watching'],
    has_gold: false,
    swimming_safety: 'Popular white water sections. Swimming spots in calmer areas.',
    fishing_season: 'Salmon: March-October; Trout: March-September',
    latitude: 53.0,
    longitude: -3.1,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '41',
    name: 'River Conwy',
    slug: 'river-conwy',
    region: 'Wales',
    length_km: 55,
    length_miles: 34,
    description: 'The River Conwy flows through Snowdonia National Park to Conwy Bay. Scenic river with mountain backdrop.',
    origin: 'Migneint, Snowdonia',
    mouth: 'Conwy Bay',
    wildlife: ['Salmon', 'Sea Trout', 'Otters', 'Herons', 'Ospreys'],
    activities: ['Fishing', 'Kayaking', 'Walking', 'Wildlife Watching'],
    has_gold: false,
    swimming_safety: 'Some swimming spots in middle sections. Tidal estuary dangerous.',
    fishing_season: 'Salmon: March-October; Trout: March-September',
    latitude: 53.28,
    longitude: -3.83,
    featured: false,
    image_url: 'https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '42',
    name: 'River Bann',
    slug: 'river-bann',
    region: 'Northern Ireland',
    length_km: 129,
    length_miles: 80,
    description: 'The River Bann is Northern Ireland\'s longest river, flowing through Lough Neagh to the Atlantic Ocean.',
    origin: 'Mourne Mountains',
    mouth: 'Atlantic Ocean at Coleraine',
    wildlife: ['Atlantic Salmon', 'Brown Trout', 'Eels', 'Otters', 'Herons', 'Kingfishers'],
    activities: ['Salmon Fishing', 'Coarse Fishing', 'Boating', 'Walking', 'Wildlife Watching'],
    has_gold: false,
    swimming_safety: 'Some designated swimming areas. Generally safe in upper sections.',
    fishing_season: 'Salmon: June-October; Coarse: Year-round',
    latitude: 55.1,
    longitude: -6.6,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1118877/pexels-photo-1118877.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '43',
    name: 'River Foyle',
    slug: 'river-foyle',
    region: 'Northern Ireland',
    length_km: 32,
    length_miles: 20,
    description: 'The River Foyle flows into Lough Foyle at Derry/Londonderry. Important for salmon fishing.',
    origin: 'Confluence of Finn and Mourne',
    mouth: 'Lough Foyle',
    wildlife: ['Atlantic Salmon', 'Sea Trout', 'Otters', 'Seals', 'Wading Birds'],
    activities: ['Salmon Fishing', 'Walking', 'Heritage Tours', 'Wildlife Watching'],
    has_gold: false,
    swimming_safety: 'Not recommended due to tidal currents and cold water.',
    fishing_season: 'Salmon: March-October',
    latitude: 55.0,
    longitude: -7.3,
    featured: false,
    image_url: 'https://images.pexels.com/photos/1179229/pexels-photo-1179229.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  },
  {
    id: '44',
    name: 'River Lagan',
    slug: 'river-lagan',
    region: 'Northern Ireland',
    length_km: 70,
    length_miles: 43,
    description: 'The River Lagan flows through Belfast, undergoing significant environmental regeneration in recent decades.',
    origin: 'Slieve Croob, County Down',
    mouth: 'Belfast Lough',
    wildlife: ['Brown Trout', 'Salmon', 'Otters', 'Kingfishers', 'Herons'],
    activities: ['Walking', 'Cycling', 'Heritage Tours', 'Fishing'],
    has_gold: false,
    swimming_safety: 'Not recommended due to urban location and tidal influence.',
    fishing_season: 'Salmon: June-October; Trout: March-September',
    latitude: 54.6,
    longitude: -5.9,
    featured: false,
    image_url: 'https://images.pexels.com/photos/534164/pexels-photo-534164.jpeg',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z'
  }
];

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'The Complete Guide to Wild Swimming in UK Rivers',
    slug: 'wild-swimming-uk-rivers-guide',
    category: 'Safety',
    excerpt: 'Essential safety tips, best locations, and what you need to know before taking the plunge into Britain\'s rivers.',
    content: null,
    image_url: 'https://images.pexels.com/photos/1118877/pexels-photo-1118877.jpeg',
    published: true,
    published_at: '2024-03-15T10:00:00Z',
    created_at: '2024-03-15T10:00:00Z'
  },
  {
    id: '2',
    title: 'Chalk Rivers: Britain\'s Rare Aquatic Treasures',
    slug: 'chalk-rivers-uk-guide',
    category: 'Conservation',
    excerpt: 'Discover why the UK hosts 85% of the world\'s chalk streams and what makes these ecosystems so special.',
    content: null,
    image_url: 'https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg',
    published: true,
    published_at: '2024-03-10T10:00:00Z',
    created_at: '2024-03-10T10:00:00Z'
  },
  {
    id: '3',
    title: 'Top 10 Rivers for Salmon Fishing in Scotland',
    slug: 'salmon-fishing-scotland-rivers',
    category: 'Fishing',
    excerpt: 'From the Tay to the Spey, explore Scotland\'s premier salmon fishing destinations and learn about seasonal patterns.',
    content: null,
    image_url: 'https://images.pexels.com/photos/2901209/pexels-photo-2901209.jpeg',
    published: true,
    published_at: '2024-03-05T10:00:00Z',
    created_at: '2024-03-05T10:00:00Z'
  },
  {
    id: '4',
    title: 'Wildlife Spotting Along the River Thames',
    slug: 'thames-wildlife-guide',
    category: 'Wildlife',
    excerpt: 'A comprehensive guide to the diverse wildlife inhabiting Britain\'s most famous river, from kingfishers to seals.',
    content: null,
    image_url: 'https://images.pexels.com/photos/460672/pexels-photo-460672.jpeg',
    published: true,
    published_at: '2024-02-28T10:00:00Z',
    created_at: '2024-02-28T10:00:00Z'
  },
  {
    id: '5',
    title: 'Gold Panning in Scottish Rivers: A Beginner\'s Guide',
    slug: 'gold-panning-scotland-guide',
    category: 'Activities',
    excerpt: 'Learn where to find gold in rivers like the Tay and Dee, plus essential techniques and legal requirements.',
    content: null,
    image_url: 'https://images.pexels.com/photos/1118877/pexels-photo-1118877.jpeg',
    published: true,
    published_at: '2024-02-20T10:00:00Z',
    created_at: '2024-02-20T10:00:00Z'
  },
  {
    id: '6',
    title: 'Understanding River Geography: From Source to Sea',
    slug: 'river-geography-uk-explained',
    category: 'Geography',
    excerpt: 'Explore how UK rivers form, flow, and shape the landscape from mountain springs to coastal estuaries.',
    content: null,
    image_url: 'https://images.pexels.com/photos/534164/pexels-photo-534164.jpeg',
    published: true,
    published_at: '2024-02-15T10:00:00Z',
    created_at: '2024-02-15T10:00:00Z'
  }
];
